name: Epic Issue
description: Use this template to create an Epic for tracking work.
title: "[Epic] "
labels: ["Increment"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Enter a detailed description of the epic."
      placeholder: "Provide detailed description of the epic."
      
  - type: input
    id: businessgoal
    attributes:
      label: Business/ Product Goal
      description: "Describe which business/ product goal is achieved through this Epic"
      placeholder: "Example: I want authentication and authorization implemented so that my users can use this app."
  
  - type: input
    id: assigned_to
    attributes:
      label: Assigned To
      description: "Assign to person responsible for this epic."
      placeholder: "username"

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: "Select the current status of this epic."
      options:
        - "New"
        - "Active"
        - "Done"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Provide any additional context (e.g., wireframes, documents). You can attach files by dragging them into the issue body."
      placeholder: "Additional context, links, or instructions..."
