name: Epic
description: Use this template to create an Epic for tracking work.
title: "[Epic] "
labels: ["Increment"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Enter a detailed description of the epic."
      
  - type: input
    id: businessgoal
    attributes:
      label: Business/ Product Goal
      description: "Short description of business value achieved through this Epic"

  - type: dropdown
    id: business_priority
    attributes:
      label: Business Priority
      description: "Select the business priority of this epic."
      options:
        - "High"
        - "Medium"
        - "Low"
        
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: "Select the current status of this epic."
      options:
        - "New"
        - "Active"
        - "Done"
